### ISSUE TITLE
init.lua:4: bad argument #1 to 'config' (config table not found!)

### ISSUE THREAD

**Issue by pcace** [Christoph-D/esp8266-wakelight#1]
Hey, 

i am a total beginner with the ESP2866, but i gave your code a try and failed :( Maybe you can help me out? I uploaded the code to my ESP2866 with the newest build NodeMCU (3.0.0) via nodemcu-tool. This is what it looked like: 

> MacPro:src johannes$ nodemcu-tool upload --port=/dev/cu.SLAB_USBtoUART ~/Desktop/esp8266-wakelight-master/src/* --connection-delay 1000
> [NodeMCU-Tool]~ Connected 
> [device]      ~ Arch: esp8266 | Version: 3.0.0 | ChipID: 0xdc4912 | FlashID: 0x146085 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/alarms.lua" >> "alarms.lua"... 
> [connector]   ~ Transfer-Mode: hex 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/configserver.lua" >> "configserver.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/globals.lua" >> "globals.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/globals.lua.template" >> "globals.lua.template"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/init.lua" >> "init.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/ledblink.lua" >> "ledblink.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/ledrun.lua" >> "ledrun.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/ledserver.lua" >> "ledserver.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/mood.lua" >> "mood.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/sunrise_color.lua" >> "sunrise_color.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/time.lua" >> "time.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/timesync.lua" >> "timesync.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/uploadserver.lua" >> "uploadserver.lua"... 
> [NodeMCU-Tool]~ Uploading "/Users/johannes/Desktop/esp8266-wakelight-master/src/wakelighttimer.lua" >> "wakelighttimer.lua"... 
> [NodeMCU-Tool]~ Bulk File Transfer complete! 
> [NodeMCU-Tool]~ disconnecting 
> 

Then basically nothing happened (oh, i did chance the globals.lua to my needs). When i use a serial console to see what is happening, i get this: 

> 
> NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
>         branch: master
>         commit: 310faf7fcc9130a296f7f17021d48c6d717f5fb6
>         release: 3.0-master_20190907
>         release DTS: 201909070945
>         SSL: false
>         build type: float
>         LFS: 0x0
>         modules: file,gpio,net,node,rtcmem,rtctime,sntp,tm1829,tmr,uart,wifi,ws2
>  build 2019-11-28 19:11 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
> lua: cannot open globals.lc
> stack traceback:
>         [C]: in function 'dofile'
>         init.lua:1: in main chunk
>         [C]: ?
> > 

So what does lua: cannot open globals.lc mean?

Thank you so much,

Pcace

**Comment by pcace** [comment]
Hi,

i got one step further (i guess...)
i used your upload script and got lucky. "All Done!"

But now i see this in the serial communication: 

> 
> NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
>         branch: master
>         commit: 310faf7fcc9130a296f7f17021d48c6d717f5fb6
>         release: 3.0-master_20190907
>         release DTS: 201909070945
>         SSL: false
>         build type: float
>         LFS: 0x0
>         modules: file,gpio,net,node,rtcmem,rtctime,sntp,tm1829,tmr,uart,wifi,ws2
>  build 2019-11-28 19:11 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
> lua: init.lua:4: bad argument #1 to 'config' (config table not found!)
> stack traceback:
>         [C]: in function 'config'
>         init.lua:4: in main chunk
>         [C]: ?
> > 
>

**Comment by Christoph-D** [comment]
It seems the API of the "wifi" module changed.  The "wifi.sta.config" function now expects a table as a single argument instead of multiple strings:
https://nodemcu.readthedocs.io/en/master/modules/wifi/#wifistaconfig

This looks like a bug in esp8266-wakelight, thanks for reporting this.  I currently don't have the right hardware and time to fix this.  If this is the only function signature that changed in the wifi module, the fix should not be too hard.

**Comment by pcace** [comment]
Hey, i got a little bit further! I have the program running, kind of:

```
NodeMCU 2.2.0.0 built with Docker provided by frightanic.com
.branch: master
.commit: 11592951b90707cdcb6d751876170bf4da82850d
.SSL: false
.Build type: float
.LFS: disabled
.modules: adc,bit,dht,file,gpio,i2c,mqtt,net,node,ow,spi,tmr,uart,wifi
 build created on 2019-12-07 23:52
 powered by Lua 5.1.4 on SDK 2.2.1(6ab97e9)
> Config done, IP is 192.168.2.168
LED-Server started
PANIC: unprotected error in call to Lua API (bad argument #2 to 'set' (index out of range))

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 27780, room 16 
tail 4
chksum 0xbc
load 0x3ffe8000, len 2188, room 4 
tail 8
chksum 0xba
load 0x3ffe888c, len 136, room 0 
tail 8
chksum 0xf2
csum 0xf2
å¬ú‰.Éo‰ísÉÚo|Ï.å.õd$`..#íú..æÑ2rí.lúN‡.Éo„..l`.Ñ‚r€lÑ$.å...l`.Ñ‚s≤pÉ‰$.å....l`.Ñ‚r€l.èæ.å...$l`.{$é.êo.Ñü¬cc.ÑÑ".|l.Bè.c.‰è¬.lc‰ÚnÓ.2NN‚....å#€‚n.ÏéÑ.l..$Ïådè|Ïl.é.lÄ.o¸.Ñæ.#".llÏÑè..c...åû„åc.l.Ñb.{$r.
```

Do you have any idea, what the Problem here could be?

Thanks a lot!!!
